In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./dataset/tutor_report_ALL_YEARS.csv")

In [3]:
df.head()

,service_type,student,student_location,lesson_date,date_confirmed,type,"lesson_price,_usd","tutor_payout,_pct","earning,_usd",academic_year
0,Preply Marketplace,Cong .,Germany,2021-10-16 07:00:00,2021-10-16 07:00:00,Trial,9.0,-,-,2021-2022
1,Preply Marketplace,Fatih .,Turkey,2021-10-18 08:30:00,2021-10-18 08:30:00,Trial,9.0,-,-,2021-2022
2,Preply Marketplace,Fatih .,Turkey,2021-10-19 06:00:00,2021-10-19 06:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022
3,Preply Marketplace,.,United Kingdom,2021-10-19 07:00:00,2021-10-19 07:00:00,Trial,10.0,-,-,2021-2022
4,Preply Marketplace,Cong .,Germany,2021-10-19 18:00:00,2021-10-19 18:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022

In [4]:
print("── Column Data Types ────────────────────────────────────────────────────")
print(df.dtypes)

print("\n── Shape ────────────────────────────────────────────────────────────────")
print(f"Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}")

── Column Data Types ────────────────────────────────────────────────────
service_type          object
student               object
student_location      object
lesson_date           object
date_confirmed        object
type                  object
lesson_price,_usd    float64
tutor_payout,_pct     object
earning,_usd          object
academic_year         object
dtype: object

── Shape ────────────────────────────────────────────────────────────────
Rows: 2,994  |  Columns: 10

In [5]:
df.head(10)

,service_type,student,student_location,lesson_date,date_confirmed,type,"lesson_price,_usd","tutor_payout,_pct","earning,_usd",academic_year
0,Preply Marketplace,Cong .,Germany,2021-10-16 07:00:00,2021-10-16 07:00:00,Trial,9.0,-,-,2021-2022
1,Preply Marketplace,Fatih .,Turkey,2021-10-18 08:30:00,2021-10-18 08:30:00,Trial,9.0,-,-,2021-2022
2,Preply Marketplace,Fatih .,Turkey,2021-10-19 06:00:00,2021-10-19 06:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022
3,Preply Marketplace,.,United Kingdom,2021-10-19 07:00:00,2021-10-19 07:00:00,Trial,10.0,-,-,2021-2022
4,Preply Marketplace,Cong .,Germany,2021-10-19 18:00:00,2021-10-19 18:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022
5,Preply Marketplace,Olesya R.,France,2021-10-22 06:00:00,2021-10-22 06:00:00,Trial,10.0,-,-,2021-2022
6,Preply Marketplace,.,Germany,2021-10-22 08:00:00,2021-10-22 08:00:00,Trial,9.0,-,-,2021-2022
7,Preply Marketplace,Mario .,United Kingdom,2021-10-22 17:30:00,2021-10-22 17:30:00,Trial,10.0,-,-,2021-2022
8,Preply Marketplace,.,France,2021-10-22 20:00:00,2021-10-22 20:00:00,Trial,12.0,-,-,2021-2022
9,Preply Marketplace,Fatih .,Turkey,2021-10-23 06:00:00,2021-10-23 06:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022

In [6]:
df['lesson_date'] = pd.to_datetime(df['lesson_date'], errors='coerce')
df['date_confirmed'] = pd.to_datetime(df['date_confirmed'], errors='coerce')

In [7]:
# # ── Unique Students (smart logic for "." names) ───────────────────────────────

# # For named students → identity is just their name
# # For "." students   → identity is (name + location + price) combined

# df["student_id"] = df.apply(
#     lambda row: (
#         row["student"]                                          # named students → name alone
#         if row["student"].strip() != "."
#         else f"._{row['student_location']}_{row['lesson_price,_usd']}"   # "." students → name + location + price
#     ),
#     axis=1
# )

# unique_students = df["student_id"].nunique()

# print(f"👨‍🎓 Total unique students (smart count) : {unique_students}")
# print(f"\n── Breakdown ────────────────────────────────────────────────────────────")
# print(f"   Named students   : {df[df['student'].str.strip() != '.']['student'].nunique()}")
# print(f"   '.' students     : {df[df['student'].str.strip() == '.']['student_id'].nunique()}")

In [8]:
# # ── Display all 115 unique students ───────────────────────────────────────────

# named = df[df["student"].str.strip() != "."][["student"]].drop_duplicates().sort_values("student")
# named.columns = ["student_display"]
# named["location"] = "-"
# named["price"] = "-"

# dot = (df[df["student"].str.strip() == "."]
#        .groupby(["student_id", "student_location", "lesson_price,_usd"])
#        .first()
#        .reset_index()[["student_id", "student_location", "lesson_price,_usd"]])
# dot.columns = ["student_display", "location", "price"]

# all_students = pd.concat([named, dot], ignore_index=True).sort_values("student_display")
# all_students.index = range(1, len(all_students) + 1)

# display(all_students)
# print(f"\n✅ Total: {len(all_students)} unique students")

In [9]:
df['tutor_payout,_pct'] = (
    df['tutor_payout,_pct']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.strip()
    .pipe(pd.to_numeric, errors='coerce')
)

In [10]:
df['earning,_usd'] = (
    df['earning,_usd']
    .astype(str)
    .str.replace('[$,]', '', regex=True)
    .str.strip()
    .pipe(pd.to_numeric, errors='coerce')
)

In [11]:
print("── Column Data Types ────────────────────────────────────────────────────")
print(df.dtypes)

print("\n── Shape ────────────────────────────────────────────────────────────────")
print(f"Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}")

── Column Data Types ────────────────────────────────────────────────────
service_type                 object
student                      object
student_location             object
lesson_date          datetime64[ns]
date_confirmed       datetime64[ns]
type                         object
lesson_price,_usd           float64
tutor_payout,_pct           float64
earning,_usd                float64
academic_year                object
dtype: object

── Shape ────────────────────────────────────────────────────────────────
Rows: 2,994  |  Columns: 10

In [12]:
df.head()

,service_type,student,student_location,lesson_date,date_confirmed,type,"lesson_price,_usd","tutor_payout,_pct","earning,_usd",academic_year
0,Preply Marketplace,Cong .,Germany,2021-10-16 07:00:00,2021-10-16 07:00:00,Trial,9.0,NaN,NaN,2021-2022
1,Preply Marketplace,Fatih .,Turkey,2021-10-18 08:30:00,2021-10-18 08:30:00,Trial,9.0,NaN,NaN,2021-2022
2,Preply Marketplace,Fatih .,Turkey,2021-10-19 06:00:00,2021-10-19 06:00:00,Non-trial lesson,9.0,67.0,6.03,2021-2022
3,Preply Marketplace,.,United Kingdom,2021-10-19 07:00:00,2021-10-19 07:00:00,Trial,10.0,NaN,NaN,2021-2022
4,Preply Marketplace,Cong .,Germany,2021-10-19 18:00:00,2021-10-19 18:00:00,Non-trial lesson,9.0,67.0,6.03,2021-2022

In [13]:
print(df.isnull().sum())

service_type           0
student                0
student_location       0
lesson_date           97
date_confirmed        97
type                   0
lesson_price,_usd      0
tutor_payout,_pct    207
earning,_usd         207
academic_year          0
dtype: int64

In [14]:
# Select only the columns I need
df = df[['student', 'student_location', 'lesson_date', 'type', 'lesson_price,_usd', 'academic_year']]

In [15]:
df.head()

,student,student_location,lesson_date,type,"lesson_price,_usd",academic_year
0,Cong .,Germany,2021-10-16 07:00:00,Trial,9.0,2021-2022
1,Fatih .,Turkey,2021-10-18 08:30:00,Trial,9.0,2021-2022
2,Fatih .,Turkey,2021-10-19 06:00:00,Non-trial lesson,9.0,2021-2022
3,.,United Kingdom,2021-10-19 07:00:00,Trial,10.0,2021-2022
4,Cong .,Germany,2021-10-19 18:00:00,Non-trial lesson,9.0,2021-2022

In [18]:
df.dtypes

student                      object
student_location             object
lesson_date          datetime64[ns]
type                         object
lesson_price,_usd           float64
academic_year                object
dtype: object

In [19]:
print(df.isnull().sum())

student               0
student_location      0
lesson_date          97
type                  0
lesson_price,_usd     0
academic_year         0
dtype: int64

In [20]:
print(df[df['lesson_date'].isnull()])

          student student_location lesson_date                  type  \
1757         Luca            Italy         NaT     Unused lesson (1)
1758  Matthias K.            Italy         NaT    Unused lessons (2)
1764          Leo   United Kingdom         NaT     Unused lesson (1)
1769      Lars M.      Netherlands         NaT    Unused lessons (2)
1786       Melody           Canada         NaT    Unused lessons (8)
...           ...              ...         ...                   ...
2925      Nicolas       Luxembourg         NaT    Unused lessons (7)
2948     Nader A.    United States         NaT  Unused lessons (0.5)
2967          Leo          Germany         NaT    Unused lessons (2)
2968         iris    United States         NaT    Unused lessons (2)
2987        K. C.    United States         NaT     Unused lesson (1)

      lesson_price,_usd academic_year
1757               25.0     2024-2025
1758               40.0     2024-2025
1764               25.0     2024-2025
1769               40.0     2024-2025
1786              160.0     2024-2025
...                 ...           ...
2925              112.0     2025-2026
2948               13.5     2025-2026
2967               32.0     2025-2026
2968               60.0     2025-2026
2987               27.0     2025-2026

[97 rows x 6 columns]

In [21]:
df['lesson_date'].fillna(pd.Timestamp('2026-05-17'), inplace=True)

In [22]:
print(df.isnull().sum())

student              0
student_location     0
lesson_date          0
type                 0
lesson_price,_usd    0
academic_year        0
dtype: int64

In [26]:
# See all rows where student name is "."
dot_students = df[df['student'] == ' .']
print(dot_students[['student', 'student_location', 'lesson_price,_usd']].drop_duplicates())
print("\nTotal rows:", len(dot_students))

     student student_location  lesson_price,_usd
3          .   United Kingdom               10.0
6          .          Germany                9.0
8          .           France               12.0
15         .            Spain               12.0
21         .   United Kingdom               12.0
44         .   United Kingdom               15.0
67         .          Germany               15.0
80         .           France               15.0
93         .            Italy               15.0
96         .    United States               15.0
101        .      Switzerland               17.0
166        .    United States               17.0
181        .            Italy               20.0
221        .          Germany               17.0
238        .           Israel               17.0
306        .         Pakistan               17.0
431        .           Kuwait               20.0
605        .    United States               20.0
1182       .           France                8.5
1206       .           France               17.0

Total rows: 132

In [24]:
df.head(10)

,student,student_location,lesson_date,type,"lesson_price,_usd",academic_year
0,Cong .,Germany,2021-10-16 07:00:00,Trial,9.0,2021-2022
1,Fatih .,Turkey,2021-10-18 08:30:00,Trial,9.0,2021-2022
2,Fatih .,Turkey,2021-10-19 06:00:00,Non-trial lesson,9.0,2021-2022
3,.,United Kingdom,2021-10-19 07:00:00,Trial,10.0,2021-2022
4,Cong .,Germany,2021-10-19 18:00:00,Non-trial lesson,9.0,2021-2022
5,Olesya R.,France,2021-10-22 06:00:00,Trial,10.0,2021-2022
6,.,Germany,2021-10-22 08:00:00,Trial,9.0,2021-2022
7,Mario .,United Kingdom,2021-10-22 17:30:00,Trial,10.0,2021-2022
8,.,France,2021-10-22 20:00:00,Trial,12.0,2021-2022
9,Fatih .,Turkey,2021-10-23 06:00:00,Non-trial lesson,9.0,2021-2022

In [27]:
mask = df['student'] == ' .'

df.loc[mask, 'student'] = df.loc[mask].groupby(
    ['student_location', 'lesson_price,_usd']
).ngroup().add(1).apply(lambda x: f'Unknown_{x}')

# Verify
print(df[df['student'].str.startswith('Unknown')][['student', 'student_location', 'lesson_price,_usd']].drop_duplicates().sort_values('student'))

         student student_location  lesson_price,_usd
1182   Unknown_1           France                8.5
181   Unknown_10            Italy               20.0
431   Unknown_11           Kuwait               20.0
306   Unknown_12         Pakistan               17.0
15    Unknown_13            Spain               12.0
101   Unknown_14      Switzerland               17.0
3     Unknown_15   United Kingdom               10.0
21    Unknown_16   United Kingdom               12.0
44    Unknown_17   United Kingdom               15.0
96    Unknown_18    United States               15.0
166   Unknown_19    United States               17.0
8      Unknown_2           France               12.0
605   Unknown_20    United States               20.0
80     Unknown_3           France               15.0
1206   Unknown_4           France               17.0
6      Unknown_5          Germany                9.0
67     Unknown_6          Germany               15.0
221    Unknown_7          Germany               17.0
238    Unknown_8           Israel               17.0
93     Unknown_9            Italy               15.0

In [29]:
print(df['student_location'].unique())
print("\nTotal unique locations:", df['student_location'].nunique())

['Germany' 'Turkey' 'United Kingdom' 'France' 'Spain' 'Canada'
 'Netherlands' 'United States' 'Italy' 'Switzerland' 'Israel' 'Pakistan'
 'Kuwait' 'United Arab Emirates' 'Luxembourg' 'Belgium' 'Greece' 'PR'
 'Japan' 'Austria' 'Australia' 'Taiwan' 'Ireland' 'Mexico' 'Singapore'
 'Sweden' 'China']

Total unique locations: 27

In [30]:
print(df['student_location'].value_counts())

United States           1242
United Kingdom           548
Germany                  327
Italy                    241
France                    97
Spain                     97
Luxembourg                87
Canada                    70
Netherlands               64
United Arab Emirates      60
Israel                    44
Turkey                    32
Belgium                   19
Switzerland               16
Kuwait                    13
Japan                     11
Singapore                  8
PR                         5
Australia                  3
Ireland                    2
Mexico                     2
Greece                     1
Pakistan                   1
Austria                    1
Taiwan                     1
Sweden                     1
China                      1
Name: student_location, dtype: int64

In [31]:
print(df[df['student_location'] == 'PR'][['student', 'student_location', 'lesson_price,_usd', 'academic_year']])

       student student_location  lesson_price,_usd academic_year
1589  Leena H.               PR               10.0     2024-2025
1594  Leena H.               PR               20.0     2024-2025
1605  Leena H.               PR               20.0     2024-2025
1640  Leena H.               PR               20.0     2024-2025
1676  Leena H.               PR               20.0     2024-2025

In [32]:
df['student_location'] = df['student_location'].str.replace('PR', 'Puerto Rico', regex=False)

In [33]:
print(df['student_location'].value_counts())

United States           1242
United Kingdom           548
Germany                  327
Italy                    241
France                    97
Spain                     97
Luxembourg                87
Canada                    70
Netherlands               64
United Arab Emirates      60
Israel                    44
Turkey                    32
Belgium                   19
Switzerland               16
Kuwait                    13
Japan                     11
Singapore                  8
Puerto Rico                5
Australia                  3
Ireland                    2
Mexico                     2
Greece                     1
Pakistan                   1
Austria                    1
Taiwan                     1
Sweden                     1
China                      1
Name: student_location, dtype: int64

In [34]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 26

In [35]:
for col in ['student', 'student_location', 'type', 'academic_year']:
    df[col] = df[col].str.strip().str.title()

print(df['type'].unique())
print(df['academic_year'].unique())

['Trial' 'Non-Trial Lesson' 'Unused Lesson (1)' 'Unused Lessons (2)'
 'Unused Lessons (8)' 'Unused Lessons (4)' 'Unused Lessons (3)'
 'Unused Lessons (9)' 'Unused Lessons (6)' 'Unused Lessons (5)'
 'Unused Lessons (1.5)' 'Unused Lessons (0.5)' 'Unused Lessons (7)'
 'Unused Lessons (10)']
['2021-2022' '2022-2023' '2023-2024' '2024-2025' '2025-2026']

In [36]:
# Collapse all Unused into one category
df['type'] = df['type'].str.replace(r'Unused Lessons?\s*\(.*\)', 'Unused Lessons', regex=True)

In [37]:
print(df['type'].unique())
print(df['academic_year'].unique())

['Trial' 'Non-Trial Lesson' 'Unused Lessons']
['2021-2022' '2022-2023' '2023-2024' '2024-2025' '2025-2026']

In [38]:
# Inspect them first
print(df[df.duplicated(keep=False)].sort_values('student'))

         student student_location         lesson_date            type  \
2129  Ardalan T.    United States 2026-05-17 00:00:00  Unused Lessons
2417  Ardalan T.    United States 2026-05-17 00:00:00  Unused Lessons
2873   Benoit G.           Canada 2026-05-17 00:00:00  Unused Lessons
2748   Benoit G.           Canada 2026-05-17 00:00:00  Unused Lessons
2792  Cameron M.    United States 2026-05-17 00:00:00  Unused Lessons
2500  Cameron M.    United States 2026-05-17 00:00:00  Unused Lessons
2858     Johanna           France 2026-05-17 00:00:00  Unused Lessons
2551     Johanna           France 2026-05-17 00:00:00  Unused Lessons
2170     Johanna           France 2026-05-17 00:00:00  Unused Lessons
2400     Johanna           France 2026-05-17 00:00:00  Unused Lessons
2419       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2911       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2848       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2709       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2669       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2580       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2987       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
1977       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2029       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2070       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2211       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
2130       K. C.    United States 2026-05-17 00:00:00  Unused Lessons
1960     Lars M.      Netherlands 2026-05-17 00:00:00  Unused Lessons
2013     Lars M.      Netherlands 2026-05-17 00:00:00  Unused Lessons
2234     Lars M.      Netherlands 2026-05-17 00:00:00  Unused Lessons
1769     Lars M.      Netherlands 2026-05-17 00:00:00  Unused Lessons
2367     Lars M.      Netherlands 2026-05-17 00:00:00  Unused Lessons
2072     Lars M.      Netherlands 2026-05-17 00:00:00  Unused Lessons
2870    Nader A.    United States 2026-05-17 00:00:00  Unused Lessons
2948    Nader A.    United States 2026-05-17 00:00:00  Unused Lessons
2641    Nader A.    United States 2026-05-17 00:00:00  Unused Lessons
2699    Nader A.    United States 2026-05-17 00:00:00  Unused Lessons
2815     Nicolas       Luxembourg 2026-05-17 00:00:00  Unused Lessons
2235     Nicolas       Luxembourg 2026-05-17 00:00:00  Unused Lessons
2747     Nicolas       Luxembourg 2026-05-17 00:00:00  Unused Lessons
1931     Nicolas       Luxembourg 2026-05-17 00:00:00  Unused Lessons
2670   Parisa Z.   United Kingdom 2026-05-17 00:00:00  Unused Lessons
2212   Parisa Z.   United Kingdom 2026-05-17 00:00:00  Unused Lessons
2071   Parisa Z.   United Kingdom 2026-05-17 00:00:00  Unused Lessons
2490   Parisa Z.   United Kingdom 2026-05-17 00:00:00  Unused Lessons
2420   Parisa Z.   United Kingdom 2026-05-17 00:00:00  Unused Lessons
2131   Parisa Z.   United Kingdom 2026-05-17 00:00:00  Unused Lessons
2787   Parisa Z.   United Kingdom 2026-05-17 00:00:00  Unused Lessons
81     Unknown_3           France 2022-01-16 21:30:00           Trial
80     Unknown_3           France 2022-01-16 21:30:00           Trial

      lesson_price,_usd academic_year
2129               25.0     2024-2025
2417               25.0     2024-2025
2873               56.0     2025-2026
2748               56.0     2025-2026
2792               81.0     2025-2026
2500               81.0     2025-2026
2858               32.0     2025-2026
2551               32.0     2025-2026
2170               16.0     2024-2025
2400               16.0     2024-2025
2419               27.0     2024-2025
2911               54.0     2025-2026
2848               54.0     2025-2026
2709               27.0     2025-2026
2669               54.0     2025-2026
2580               27.0     2025-2026
2987               27.0     2025-2026
1977               27.0     2024-2025
2029               27.0     2024-2025
2070               54.0     2024-2025
2211               54.0     2024-2025
2130               27.0     2024-2025
1960               40.0     2024-2025
2013               60.0     2024-2025
2234               60.0     2024-2025
1769               40.0     2024-2025
2367              120.0     2024-2025
2072              120.0     2024-2025
2870               13.5     2025-2026
2948               13.5     2025-2026
2641               54.0     2025-2026
2699               54.0     2025-2026
2815               16.0     2025-2026
2235               48.0     2024-2025
2747               16.0     2025-2026
1931               48.0     2024-2025
2670               17.0     2025-2026
2212               17.0     2024-2025
2071               17.0     2024-2025
2490               17.0     2025-2026
2420               17.0     2024-2025
2131               17.0     2024-2025
2787               17.0     2025-2026
81                 15.0     2021-2022
80                 15.0     2021-2022

In [39]:
# Option A - collapse unused lesson types
df['type'] = df['type'].str.replace(r'Unused Lessons?\s*\(.*\)', 'Unused Lessons', regex=True)

In [41]:
# Drop only the one real duplicate
df.drop_duplicates(inplace=True)

In [42]:
# Verify
print("Remaining duplicates:", df.duplicated().sum())
print("Shape:", df.shape)
print(df['type'].unique())

Remaining duplicates: 0
Shape: (2968, 6)
['Trial' 'Non-Trial Lesson' 'Unused Lessons']

In [43]:
df.to_csv('clean_dataset.csv', index=False)