In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./dataset/tutor_report_ALL_YEARS.csv")

In [3]:
df.head()

,service_type,student,student_location,lesson_date,date_confirmed,type,"lesson_price,_usd","tutor_payout,_pct","earning,_usd",academic_year
0,Preply Marketplace,Cong .,Germany,2021-10-16 07:00:00,2021-10-16 07:00:00,Trial,9.0,-,-,2021-2022
1,Preply Marketplace,Fatih .,Turkey,2021-10-18 08:30:00,2021-10-18 08:30:00,Trial,9.0,-,-,2021-2022
2,Preply Marketplace,Fatih .,Turkey,2021-10-19 06:00:00,2021-10-19 06:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022
3,Preply Marketplace,.,United Kingdom,2021-10-19 07:00:00,2021-10-19 07:00:00,Trial,10.0,-,-,2021-2022
4,Preply Marketplace,Cong .,Germany,2021-10-19 18:00:00,2021-10-19 18:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022

In [4]:
print("── Column Data Types ────────────────────────────────────────────────────")
print(df.dtypes)

print("\n── Shape ────────────────────────────────────────────────────────────────")
print(f"Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}")

── Column Data Types ────────────────────────────────────────────────────
service_type          object
student               object
student_location      object
lesson_date           object
date_confirmed        object
type                  object
lesson_price,_usd    float64
tutor_payout,_pct     object
earning,_usd          object
academic_year         object
dtype: object

── Shape ────────────────────────────────────────────────────────────────
Rows: 2,994  |  Columns: 10

In [5]:
df.head(10)

,service_type,student,student_location,lesson_date,date_confirmed,type,"lesson_price,_usd","tutor_payout,_pct","earning,_usd",academic_year
0,Preply Marketplace,Cong .,Germany,2021-10-16 07:00:00,2021-10-16 07:00:00,Trial,9.0,-,-,2021-2022
1,Preply Marketplace,Fatih .,Turkey,2021-10-18 08:30:00,2021-10-18 08:30:00,Trial,9.0,-,-,2021-2022
2,Preply Marketplace,Fatih .,Turkey,2021-10-19 06:00:00,2021-10-19 06:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022
3,Preply Marketplace,.,United Kingdom,2021-10-19 07:00:00,2021-10-19 07:00:00,Trial,10.0,-,-,2021-2022
4,Preply Marketplace,Cong .,Germany,2021-10-19 18:00:00,2021-10-19 18:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022
5,Preply Marketplace,Olesya R.,France,2021-10-22 06:00:00,2021-10-22 06:00:00,Trial,10.0,-,-,2021-2022
6,Preply Marketplace,.,Germany,2021-10-22 08:00:00,2021-10-22 08:00:00,Trial,9.0,-,-,2021-2022
7,Preply Marketplace,Mario .,United Kingdom,2021-10-22 17:30:00,2021-10-22 17:30:00,Trial,10.0,-,-,2021-2022
8,Preply Marketplace,.,France,2021-10-22 20:00:00,2021-10-22 20:00:00,Trial,12.0,-,-,2021-2022
9,Preply Marketplace,Fatih .,Turkey,2021-10-23 06:00:00,2021-10-23 06:00:00,Non-trial lesson,9.0,67.00,6.03,2021-2022

In [6]:
df['lesson_date'] = pd.to_datetime(df['lesson_date'], errors='coerce')
df['date_confirmed'] = pd.to_datetime(df['date_confirmed'], errors='coerce')

In [7]:
# # ── Unique Students (smart logic for "." names) ───────────────────────────────

# # For named students → identity is just their name
# # For "." students   → identity is (name + location + price) combined

# df["student_id"] = df.apply(
#     lambda row: (
#         row["student"]                                          # named students → name alone
#         if row["student"].strip() != "."
#         else f"._{row['student_location']}_{row['lesson_price,_usd']}"   # "." students → name + location + price
#     ),
#     axis=1
# )

# unique_students = df["student_id"].nunique()

# print(f"👨‍🎓 Total unique students (smart count) : {unique_students}")
# print(f"\n── Breakdown ────────────────────────────────────────────────────────────")
# print(f"   Named students   : {df[df['student'].str.strip() != '.']['student'].nunique()}")
# print(f"   '.' students     : {df[df['student'].str.strip() == '.']['student_id'].nunique()}")

In [8]:
# # ── Display all 115 unique students ───────────────────────────────────────────

# named = df[df["student"].str.strip() != "."][["student"]].drop_duplicates().sort_values("student")
# named.columns = ["student_display"]
# named["location"] = "-"
# named["price"] = "-"

# dot = (df[df["student"].str.strip() == "."]
#        .groupby(["student_id", "student_location", "lesson_price,_usd"])
#        .first()
#        .reset_index()[["student_id", "student_location", "lesson_price,_usd"]])
# dot.columns = ["student_display", "location", "price"]

# all_students = pd.concat([named, dot], ignore_index=True).sort_values("student_display")
# all_students.index = range(1, len(all_students) + 1)

# display(all_students)
# print(f"\n✅ Total: {len(all_students)} unique students")

In [9]:
df['tutor_payout,_pct'] = (
    df['tutor_payout,_pct']
    .astype(str)
    .str.replace('%', '', regex=False)
    .str.strip()
    .pipe(pd.to_numeric, errors='coerce')
)

In [10]:
df['earning,_usd'] = (
    df['earning,_usd']
    .astype(str)
    .str.replace('[$,]', '', regex=True)
    .str.strip()
    .pipe(pd.to_numeric, errors='coerce')
)

In [11]:
print("── Column Data Types ────────────────────────────────────────────────────")
print(df.dtypes)

print("\n── Shape ────────────────────────────────────────────────────────────────")
print(f"Rows: {df.shape[0]:,}  |  Columns: {df.shape[1]}")

── Column Data Types ────────────────────────────────────────────────────
service_type                 object
student                      object
student_location             object
lesson_date          datetime64[ns]
date_confirmed       datetime64[ns]
type                         object
lesson_price,_usd           float64
tutor_payout,_pct           float64
earning,_usd                float64
academic_year                object
dtype: object

── Shape ────────────────────────────────────────────────────────────────
Rows: 2,994  |  Columns: 10

In [12]:
df.head()

,service_type,student,student_location,lesson_date,date_confirmed,type,"lesson_price,_usd","tutor_payout,_pct","earning,_usd",academic_year
0,Preply Marketplace,Cong .,Germany,2021-10-16 07:00:00,2021-10-16 07:00:00,Trial,9.0,NaN,NaN,2021-2022
1,Preply Marketplace,Fatih .,Turkey,2021-10-18 08:30:00,2021-10-18 08:30:00,Trial,9.0,NaN,NaN,2021-2022
2,Preply Marketplace,Fatih .,Turkey,2021-10-19 06:00:00,2021-10-19 06:00:00,Non-trial lesson,9.0,67.0,6.03,2021-2022
3,Preply Marketplace,.,United Kingdom,2021-10-19 07:00:00,2021-10-19 07:00:00,Trial,10.0,NaN,NaN,2021-2022
4,Preply Marketplace,Cong .,Germany,2021-10-19 18:00:00,2021-10-19 18:00:00,Non-trial lesson,9.0,67.0,6.03,2021-2022

In [13]:
print(df.isnull().sum())

service_type           0
student                0
student_location       0
lesson_date           97
date_confirmed        97
type                   0
lesson_price,_usd      0
tutor_payout,_pct    207
earning,_usd         207
academic_year          0
dtype: int64

In [14]:
# Select only the columns I need
df = df[['student', 'student_location', 'lesson_date', 'type', 'lesson_price,_usd', 'academic_year']]

In [15]:
df.head()

,student,student_location,lesson_date,type,"lesson_price,_usd",academic_year
0,Cong .,Germany,2021-10-16 07:00:00,Trial,9.0,2021-2022
1,Fatih .,Turkey,2021-10-18 08:30:00,Trial,9.0,2021-2022
2,Fatih .,Turkey,2021-10-19 06:00:00,Non-trial lesson,9.0,2021-2022
3,.,United Kingdom,2021-10-19 07:00:00,Trial,10.0,2021-2022
4,Cong .,Germany,2021-10-19 18:00:00,Non-trial lesson,9.0,2021-2022

In [18]:
df.dtypes

student                      object
student_location             object
lesson_date          datetime64[ns]
type                         object
lesson_price,_usd           float64
academic_year                object
dtype: object

In [19]:
print(df.isnull().sum())

student               0
student_location      0
lesson_date          97
type                  0
lesson_price,_usd     0
academic_year         0
dtype: int64

In [20]:
print(df[df['lesson_date'].isnull()])

          student student_location lesson_date                  type  \
1757         Luca            Italy         NaT     Unused lesson (1)
1758  Matthias K.            Italy         NaT    Unused lessons (2)
1764          Leo   United Kingdom         NaT     Unused lesson (1)
1769      Lars M.      Netherlands         NaT    Unused lessons (2)
1786       Melody           Canada         NaT    Unused lessons (8)
...           ...              ...         ...                   ...
2925      Nicolas       Luxembourg         NaT    Unused lessons (7)
2948     Nader A.    United States         NaT  Unused lessons (0.5)
2967          Leo          Germany         NaT    Unused lessons (2)
2968         iris    United States         NaT    Unused lessons (2)
2987        K. C.    United States         NaT     Unused lesson (1)

      lesson_price,_usd academic_year
1757               25.0     2024-2025
1758               40.0     2024-2025
1764               25.0     2024-2025
1769               40.0     2024-2025
1786              160.0     2024-2025
...                 ...           ...
2925              112.0     2025-2026
2948               13.5     2025-2026
2967               32.0     2025-2026
2968               60.0     2025-2026
2987               27.0     2025-2026

[97 rows x 6 columns]